ASPNetApp/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPNetApp.Models;

namespace ASPNetApp.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ASPNetAppContext _context;
        private string searchString;

        public MoviesController(ASPNetAppContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index(string searchString)
        {
            var movies = from m in _context.Movie
                         select m;

            if(!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Title.Contains(searchString));
            }

            return View(await movies.ToListAsync());
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Genre,Price")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            _context.Movie.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }
    }
}

ASPNetApp/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPNetApp.Models;
using Microsoft.AspNetCore.Identity;

namespace ASPNetApp.Controllers
{
    public class ToDoController : Controller
    {
        private readonly ASPNetAppContext _context;
        public UserManager<User> UserManager { get; set; }

        public ToDoController(ASPNetAppContext context, UserManager<User> um)
        {
            _context = context;
            UserManager = um;

        }

        // GET: ToDoes
        public async Task<IActionResult> Index(string Importance, string searchString)
        {

            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;

            if(null != current_User)
            {
                // Use LINQ to get list of genres.
                IQueryable<string> genreQuery = from m in _context.ToDo
                                                where m.User == current_User
                                                orderby m.Importance
                                                select m.Importance;

                var toDo = from m in _context.ToDo
                           select m;

                toDo = toDo.Where(x => x.User == current_User);
                if(!string.IsNullOrEmpty(searchString))
                {
                    toDo = toDo.Where(s => s.Title.Contains(searchString));
                }

                if(!string.IsNullOrEmpty(Importance))
                {
                    toDo = toDo.Where(x => x.Importance == Importance);
                }

                var ToDoImportanceVM = new ToDoImportanceViewModel
                {
                    Importance = new SelectList(await genreQuery.Distinct().ToListAsync()),
                    toDos = await toDo.ToListAsync()
                };

                return View(ToDoImportanceVM);
            }
            return View("ErreurPasConnecte");
        }


        // GET: ToDoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;
            if(null != current_User)
            {
                if(id == null)
                {
                    return NotFound();
                }

                var toDo = await _context.ToDo
                    .FirstOrDefaultAsync(m => m.Id == id);
                if(toDo == null)
                {
                    return NotFound();
                }

                return View(toDo);
            }
            return View("ErreurPasConnecte");

        }

        // GET: ToDoes/Create
        public IActionResult Create()
        {
            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;
            if(null != current_User)
            {
                return View();
            }
            return View("ErreurPasConnecte");
        }

        // POST: ToDoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Date,Importance,Content,Deadline,ID_User")] ToDo toDo)
        {
            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;
            if(null != current_User)
            {
                if(ModelState.IsValid)
                {
                    toDo.User = current_User; 
                    _context.Add(toDo); 
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(toDo);
            }
            return View("ErreurPasConnecte");
        }

        // GET: ToDoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;
            if(null != current_User)
            {
                if(id == null)
                {
                    return NotFound();
                }

                var toDo = await _context.ToDo.FindAsync(id);
                if(toDo == null)
                {
                    return NotFound();
                }
                return View(toDo);
            }
            return View("ErreurPasConnecte");
        }

        // POST: ToDoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Date,Importance,Content,Deadline")] ToDo toDo)
        {
            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;
            if(null != current_User)
            {
                if(id != toDo.Id)
                {
                    return NotFound();
                }

                if(ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(toDo);
                        await _context.SaveChangesAsync();
                    }
                    catch(DbUpdateConcurrencyException)
                    {
                        if(!ToDoExists(toDo.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(toDo);
            }
            return View("ErreurPasConnecte");
        }

        // GET: ToDoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;
            if(null != current_User)
            {
                if(id == null)
                {
                    return NotFound();
                }

                var toDo = await _context.ToDo
                    .FirstOrDefaultAsync(m => m.Id == id);
                if(toDo == null)
                {
                    return NotFound();
                }


                return View(toDo);
            }
            return View("ErreurPasConnecte");
        }

        // POST: ToDoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var current_User = UserManager.GetUserAsync(HttpContext.User).Result;
            if(null != current_User)
            {
                var toDo = await _context.ToDo.FindAsync(id);
                _context.ToDo.Remove(toDo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View("ErreurPasConnecte");
        }

        private bool ToDoExists(int id)
        {

            return _context.ToDo.Any(e => e.Id == id);

        }
    }
}

ASPNetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FUN - @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Fun With ASP.Net Core</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movie</a></li>
                    @if(ViewContext.HttpContext.User.Identity.Name != null)
                    {
                        <li><a asp-area="" asp-controller="ToDo" asp-action="Index">ToDo</a></li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
       
    </div>
    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-white">
            &copy; 2019 - WinDev is still better - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

</body>
</html>